services:
  app:
    build: .
    container_name: websocket-server-sample
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
